#include "tinykv.grpc.pb.h" // Auto-generated by CMake
#include <grpcpp/grpcpp.h>
#include <iostream>
#include <memory>

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::Status;

using namespace tinykv;

// The logic class
class TinyServer final : public TinyKV::Service {
  Status Ping(ServerContext *context, const PingRequest *request,
              PingResponse *reply) override {
    std::cout << "[Server] Received a Ping!" << std::endl;
    reply->set_is_ready(true);
    return Status::OK;
  }

  Status Put(ServerContext *context, const PutRequest *request,
             PutResponse *reply) override {
    std::cout << "[Server] Received a PutRequest with key " << request->key()
              << "!" << std::endl;
    reply->set_operation_success(true);
    return Status::OK;
  }
};

void RunServer() {
  // TODO: Dynamically assign server listening port
  std::string server_address("0.0.0.0:50051");
  TinyServer service;

  ServerBuilder builder;
  builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
  builder.RegisterService(&service);

  std::unique_ptr<Server> server(builder.BuildAndStart());
  std::cout << "[Server] Listening on " << server_address << std::endl;
  server->Wait();
}

int main() {
  RunServer();
  return 0;
}
