#include "tinykv.grpc.pb.h" // Auto-generated by CMake
#include <grpcpp/grpcpp.h>
#include <iostream>
#include <memory>

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::Status;
using tinykv::PingRequest;
using tinykv::PingResponse;
using tinykv::TinyKV;

// The logic class
class TinyKVImpl final : public TinyKV::Service {
  Status Ping(ServerContext *context, const PingRequest *request,
              PingResponse *reply) override {
    std::cout << "[Server] Received a Ping!" << std::endl;
    reply->set_is_ready(true);
    return Status::OK;
  }
};

void RunServer() {
  std::string server_address("0.0.0.0:50051");
  TinyKVImpl service;

  ServerBuilder builder;
  builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
  builder.RegisterService(&service);

  std::unique_ptr<Server> server(builder.BuildAndStart());
  std::cout << "[Server] Listening on " << server_address << std::endl;
  server->Wait();
}

int main() {
  RunServer();
  return 0;
}
