#include "tinykv.grpc.pb.h" // Auto-generated by CMake
#include <grpcpp/grpcpp.h>
#include <iostream>
#include <memory>
#include <unordered_map>

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::Status;

using namespace tinykv;

// The logic class
class TinyServer final : public TinyKV::Service {
public:
  TinyServer() {};
  Status Ping(ServerContext *context, const PingRequest *request,
              PingResponse *reply) override {
    std::cout << "[Server] Received a Ping!" << std::endl;
    reply->set_is_ready(true);
    return Status::OK;
  }

  Status Put(ServerContext *context, const PutRequest *request,
             PutResponse *reply) override {
    std::cout << "[Server] Received a PutRequest with key: " << request->key()
              << " and value: " << request->val() << "!" << std::endl;

    // Critical code section, we use mutex to avoid race conditions
    kv_mutex.lock();
    kv_store[request->key()] = request->val();

    kv_mutex.unlock();

    reply->set_operation_success(true);
    return Status::OK;
  }
  Status Get(ServerContext *context, const GetRequest *request,
             GetResponse *reply) override {
    std::cout << "[Server] Received a GetRequest with key: " << request->key()
              << "!" << std::endl;

    // Critical code section, we use mutex to avoid race conditions
    kv_mutex.lock();
    reply->set_val(kv_store[request->key()]);

    kv_mutex.unlock();

    return Status::OK;
  }

private:
  std::unordered_map<std::string, std::string> kv_store;
  std::mutex kv_mutex;
};

void RunServer(std::string port) {
  // TODO: Dynamically assign server listening port
  std::string server_address("0.0.0.0:" + port);
  TinyServer service;

  ServerBuilder builder;
  builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
  builder.RegisterService(&service);

  std::unique_ptr<Server> server(builder.BuildAndStart());
  std::cout << "[Server] Listening on " << server_address << std::endl;
  server->Wait();
}

int main(int argc, char **argv) {
  if (argc != 2) {
    std::cerr << "Usage: ./tinykv_server <port>" << std::endl;
    return 1;
  }
  std::string port(argv[1]);
  RunServer(port);
  return 0;
}
